spring.application.name=InvenTrack

spring.datasource.driver-class-name=${datasource_driver_classname}
spring.datasource.username=${database_username}
spring.datasource.password=${database_password}
spring.datasource.url=${database_url}

spring.datasource.hikari.pool-name=inventrack-connection-pool
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5

spring.data.rest.detection-strategy=annotated

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=${hibernate_dialect}

server.shutdown=graceful

server.max-http-header-size=5MB
server.tomcat.max-http-form-post-size=15MB
spring.servlet.multipart.max-file-size=10MB

server.error.include-message=always
server.error.include-binding-errors=never
server.error.include-exception=false
server.error.include-stacktrace=never

spring.cache.type=simple

spring.h2.console.enabled=false

application.security.jwt.keystore-location=keys/inventrack_restful_service.jks
application.security.jwt.keystore-password=${keystore_password}
application.security.jwt.key-alias=${key_alias}
application.security.jwt.private-key-passphrase=${private_key_password}
application.security.jwt.access-token.subject=Access Token
application.security.jwt.access-token.validity-mins=${access_token_validity_min}
application.security.jwt.refresh-token.subject=Refresh Token
application.security.jwt.refresh-token.validity-days=${refresh_token_validity_day}
application.security.jwt.token-type=Bearer
application.security.jwt.audience=inventrack

application.accounts.signup-invitation.validity=${signup_invitation_validity_day}

client-application.url.signup-form=${client_app_signup_form_url}

oracle.cloud.credentials.config-file-path=src/main/resources/keys/config.txt
oracle.cloud.credentials.namespace=axyrkkg77yct
oracle.cloud.object-storage.bucket-name=inventrack
oracle.cloud.object-storage.avatars-folder-name=avatars
oracle.cloud.object-storage.products-folder-name=products

spring.data.rest.default-page-size=10
spring.data.rest.max-page-size=30

server.servlet.context-path=/api
server.servlet.encoding.charset=UTF-8

management.endpoint.health.show-details=when_authorized
management.endpoints.web.exposure.include=health, info, metrics

management.endpoints.web.cors.allowed-methods=GET, POST, PUT, PATCH, OPTIONS, HEAD
management.endpoints.web.cors.allowed-headers=Authorization, Content-Type
management.endpoints.web.cors.allow-credentials=false
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.max-age=7200s

spring.mail.host=${mail_host}
spring.mail.port=${mail_port}
spring.mail.protocol=smtp
spring.mail.test-connection=${mail_test_connection}
spring.mail.default-encoding=UTF-8
spring.mail.username=${mail_username}
spring.mail.password=${mail_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000
spring.mail.properties.mail.smtp.readtimeout=20000
spring.mail.properties.mail.smtp.starttls.enable=${mail_tls_enabled}

accounts.mail.from=${accounts_mail_from}

info.application.metadata.name=${spring.application.name}
info.application.metadata.version=${application_version}
info.application.metadata.description=RESTful Service for InvenTrack
info.application.developer.name=Syed Riadh Hossen
info.application.developer.email=hossensyedriadh@gmail.com
info.application.developer.url=https://github.com/hossensyedriadh
info.application.runtime=${java.specification.vendor} Java ${java.specification.version}